language: c
compiler:
    - gcc
    - clang
script: sudo make install && echo "source ./.jsh_travis_test_script.sh" | jsh --nodebug --norc

# disable all email notifications
# notifications:
#  email: false
